---
title: "Tableaux Markdown Example"
author: "Your name"
format:
  html:
    embed-resources: true
    code-fold: false
toc: true
toc-title: Sommaire
toc-depth: 4
toc-location: left
execute: 
  eval: false
  echo: true
output:
  html_document:
  number_sections: TRUE
  output-file: markdown_tables.html
---

```{r}
library(dplyr)
```

## Exemple de tableaux Markdown

### Données de fruits

Voici un tableau simple de fruits et de prix :
| fruit  | price  |
|--------|--------|
| apple  | 2.05   |
| pear   | 1.37   |
| orange | 3.09   |

Ce tableau sera correctement rendu en HTML.

```{r}
iris %>% 
  head(5)
```

### Tableau de comparaison

Comparaison des espèces :
| Species    | Sepal.Length (mean) |
|------------|---------------------|
| setosa     | 5.01                |
| versicolor | 5.94                |
| virginica  | 6.59                |

```{r}
iris %>% 
  group_by(Species) %>% 
  summarize(mean_sepal = mean(Sepal.Length))
```
