---
title: "Iris analysis"
author: "Damien Dotta"
date: "November 28, 2025"
description: "Example file for package quartify"
format:
  html:
    embed-resources: true
    code-fold: false
    number-sections: true
toc: true
toc-title: Sommaire
toc-depth: 4
toc-location: left
execute: 
  eval: false
  echo: true
output:
  html_document:
  output-file: example.html
---

```{r}
library(dplyr)
```

## Title 2

### Title 3

Start of statistical processing
Counting the number of observations by species

```{r}
iris |> 
  count(Species)
```

### Title 3

Filter the data.frame on Species "setosa"

```{r}
iris |> 
  filter(Species == "setosa")
```

#### Title 4

Select column Species

```{r}
iris %>% 
  # Select a column
  select(Species)
```

## Markdown tables in comments

You can include markdown tables in comments:

| Species    | Count |
|------------|-------|
| setosa     | 50    |
| versicolor | 50    |
| virginica  | 50    |

```{r}
iris %>%
  count(Species)
```
